import type { Metadata } from "next";
import { Geist, Geist_Mono, Newsreader, Tinos } from "next/font/google";
import '@fortawesome/fontawesome-free/css/all.min.css'; // import awesome font
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const newsreader = Newsreader({
  variable: "--font-newsreader",
  subsets: ["latin"],
});

const tinos = Tinos({
  variable: "--font-tinos",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode; 
}>) {
  return (
    <html lang="en">
      <body
        className={`${tinos.variable} antialiased`}
      >
        <div className="min-h-full">
            {children}
        </div>
      </body>
    </html>
  );
}
